---
title: "算法训练营Day 37 - 动态规划 part06"
author: "Siru Wu"
date: today
format: 
  html:
    embed-resources: true
---

对于背包问题：

**如果求组合数就是外层for循环遍历物品，内层for遍历背包。**
**如果求排列数就是外层for遍历背包，内层for循环遍历物品。**

## [322. 零钱兑换](https://leetcode.cn/problems/coin-change/description/)

> 给你一个整数数组 coins ，表示不同面额的硬币；以及一个整数 amount ，表示总金额。
> 
> 计算并返回可以凑成总金额所需的 最少的硬币个数 。如果没有任何一种硬币组合能组成总金额，返回 -1 。
> 
> 你可以认为每种硬币的数量是无限的。
>
> **示例 1：**
> 
> 输入：coins = [1, 2, 5], amount = 11   -   输出：3 
> 
> 解释：11 = 5 + 5 + 1
> 
> **示例 2：**
> 
> 输入：coins = [2], amount = 3   -  输出：-1
> 
> **示例 3：**
> 
> 输入：coins = [1], amount = 0    -    输出：0

```{python}
class Solution:
    def coinChange(self, coins: List[int], amount: int) -> int:
        dp = [float('inf')] * (amount + 1)  # 创建动态规划数组，初始值为正无穷大
        dp[0] = 0  # 初始化背包容量为0时的最小硬币数量为0

        for i in range(1, amount + 1):  # 遍历背包容量
            for j in range(len(coins)):  # 遍历硬币列表，相当于遍历物品
                if i - coins[j] >= 0 and dp[i - coins[j]] != float('inf'):  # 如果dp[i - coins[j]]不是初始值，则进行状态转移
                    dp[i] = min(dp[i - coins[j]] + 1, dp[i])  # 更新最小硬币数量

        if dp[amount] == float('inf'):  # 如果最终背包容量的最小硬币数量仍为正无穷大，表示无解
            return -1
        return dp[amount]  # 返回背包容量为amount时的最小硬币数量

```

## [279.完全平方数](给你一个整数 n ，返回 和为 n 的完全平方数的最少数量 。

> 完全平方数 是一个整数，其值等于另一个整数的平方；换句话说，其值等于一个整数自乘的积。例如，1、4、9 和 16 都是完全平方数，而 3 和 11 不是。)
>
> **示例 1：**
> 
> 输入：n = 12   -   输出：3 
> 
> 解释：12 = 4 + 4 + 4
> 
> **示例 2：**
> 
> 输入：n = 13   -   输出：2
> 
> 解释：13 = 4 + 9

```{python}
class Solution:
    def numSquares(self, n: int) -> int:
        dp = [float('inf')] * (n + 1)
        dp[0] = 0

        for i in range(1, n + 1):
            # j = 1 → 1² = 1 是最小的完全平方数
            # j = 2 → 4
            # j = 3 → 9
            # j = 4 → 16
            j = 1
            while j * j <= i:
                dp[i] = min(dp[i], dp[i - j * j] + 1)
                j += 1
        return dp[n]
```

## [139.单词拆分](https://leetcode.cn/problems/word-break/description/)

> 给你一个字符串 s 和一个字符串列表 wordDict 作为字典。如果可以利用字典中出现的一个或多个单词拼接出 s 则返回 true。
> 
> 注意：不要求字典中出现的单词全部都使用，并且字典中的单词可以重复使用。
>
> **示例 1：**
> 
> 输入: s = "leetcode", wordDict = ["leet", "code"]   -   **输出: true**
> 
> 解释: 返回 true 因为 "leetcode" 可以由 "leet" 和 "code" 拼接成。
> 
> **示例 2：**
> 
> 输入: s = "applepenapple", wordDict = ["apple", "pen"]   -   **输出: true**
> 
> 解释: 返回 true 因为 "applepenapple" 可以由 "apple" "pen" "apple" 拼接成。
     注意，你可以重复使用字典中的单词。
> 
> **示例 3：**
> 
> 输入: s = "catsandog", wordDict = ["cats", "dog", "sand", "and", "cat"]   -   **输出: false**

```{python}
class Solution:
    def wordBreak(self, s: str, wordDict: List[str]) -> bool:
        dp = [False] * (len(s) + 1)
        dp[0] = True # 空字符串是可以被“成功拆分”的

        for j in range(1, len(s) + 1):
            for word in wordDict:
                if j >= len(word):
                    dp[j] = dp[j] or (dp[j - len(word)] and word == s[j - len(word) : j])
        return dp[len(s)]

```

## [56. 携带矿石资源](https://kamacoder.com/problempage.php?pid=1066)

**题目描述:**

> 你是一名宇航员，即将前往一个遥远的行星。在这个行星上，有许多不同类型的矿石资源，每种矿石都有不同的重要性和价值。你需要选择哪些矿石带回地球，但你的宇航舱有一定的容量限制。 
> 
> 给定一个宇航舱，最大容量为 C。现在有 N 种不同类型的矿石，每种矿石有一个重量 w[i]，一个价值 v[i]，以及最多 k[i] 个可用。不同类型的矿石在地球上的市场价值不同。你需要计算如何在不超过宇航舱容量的情况下，最大化你所能获取的总价值。

**输入描述:**

> 输入共包括四行，第一行包含两个整数 C 和 N，分别表示宇航舱的容量和矿石的种类数量。 
> 
> 接下来的三行，每行包含 N 个正整数。具体如下： 
> 
> 第二行包含 N 个整数，表示 N 种矿石的重量。 
> 
> 第三行包含 N 个整数，表示 N 种矿石的价格。 
> 
> 第四行包含 N 个整数，表示 N 种矿石的可用数量上限。

**输出描述:**

> 输出一个整数，代表获取的最大价值。

**输入示例:**

> 10 3
> 
> 1 3 4
> 
> 15 20 30
> 
> 2 3 2

**输出示例:**

> 90

**提示信息:**

> 数据范围：
> 
> 1 <= C <= 2000;
> 
> 1 <= N <= 100;
> 
> 1 <= w[i], v[i], k[i] <= 1000;

```{python}


```