---
title: "算法训练营Day 8"
author: "Siru Wu"
date: today
format: 
  html:
    embed-resources: true
---

今天是 **字符串**

## [344 反转字符串](https://leetcode.cn/problems/reverse-string/description/)

> 编写一个函数，其作用是将输入的字符串反转过来。输入字符串以字符数组 s 的形式给出。
> 
> 不要给另外的数组分配额外的空间，你必须原地修改输入数组、使用 O(1) 的额外空间解决这一问题。
>
> 示例 1：
> 
> - 输入：s = ["h","e","l","l","o"]
> 
> - 输出：["o","l","l","e","h"]
> 
> 示例 2：
> 
> - 输入：s = ["H","a","n","n","a","h"]
> 
> - 输出：["h","a","n","n","a","H"]

### 双指针法

```{python}
# 这题题目里面说了 必须原地修改输入数组， Do not return anything, modify s in-place instead
# 不要给另外的数组分配额外的空间，所以我们直接修改 s
class Solution:
    def reverseString(self, s: List[str]) -> None:
        left, right = 0, len(s) - 1

        while left < right:
            s[left], s[right] = s[right], s[left]
            left += 1
            right -= 1
```

###使用range

```{python}
class Solution:
    def reverseString(self, s: List[str]) -> None:
        n = len(s)
        for i in range(n // 2):
            s[i], s[n - i - 1] = s[n - i - 1], s[i]
```

### 使用reversed

```{python}
class Solution:
    def reverseString(self, s: List[str]) -> None:
        s[:] = reversed(s)

        # 第二种解法
        # s[:] = s[::-1] 使用切片

        # 第三种解法
        # s = s.reverse()
        # xxx 但是不能写成 s = reversed(s) # 它返回的是一个反向迭代器，而不是list，相当于修改了s，就不满足题意了
```

## [541 反转字符串 II](https://programmercarl.com/0541.%E5%8F%8D%E8%BD%AC%E5%AD%97%E7%AC%A6%E4%B8%B2II.html)

> 给定一个字符串 s 和一个整数 k，从字符串开头算起，每计数至 2k 个字符，就反转这 2k 字符中的前 k 个字符。
> 
> 如果剩余字符少于 k 个，则将剩余字符全部反转。
> 
> 如果剩余字符小于 2k 但大于或等于 k 个，则反转前 k 个字符，其余字符保持原样。
> 
> 示例 1：
> 
> - 输入：s = "abcdefg", k = 2
> 
> - 输出："bacdfeg"
> 
> 示例 2：
> 
> - 输入：s = "abcd", k = 2
> 
> - 输出："bacd"

```{python}
class Solution(object):
    def reverseStr(self, s, k):
        """
        :type s: str
        :type k: int
        :rtype: str
        """
        # rtype: str 说明 返回值类型必须是字符串
        s = list(s) # 字符串转成列表，方便原地修改

        for i in range(0, len(s), 2 * k): # 每次跳 2k 个字符
            # 翻转区间 [i, i+k)
            s[i : i + k] = reversed(s[i : i + k])

        return ''.join(s) # 题目要求 返回字符串，而不是list
```

## [Kamacode 54 替换数字](https://kamacoder.com/problempage.php?pid=1064)

> 给定一个字符串 s，它包含小写字母和数字字符，请编写一个函数，将字符串中的字母字符保持不变，而将每个数字字符替换为number。 例如，对于输入字符串 "a1b2c3"，函数应该将其转换为 "anumberbnumbercnumber"。
> 
> - 输入描述：输入一个字符串 s,s 仅包含小写字母和数字字符。
> 
> - 输出描述：打印一个新的字符串，其中每个数字字符都被替换为了number
> 
> - 输入示例：a1b2c3
> 
> - 输出示例：anumberbnumbercnumber
> 
> 数据范围：
> 
> 1 <= s.length < 10000。

### 直接替换

```{python}
class Solution:
    def replaceDigits(self, s:str) -> str:
        # 在python里面 字符串不能直接修改
        # 所以我们要 新建一个容器，一边遍历原字符串，一边把结果拼进去
        result = []

        for c in s:
            if '0' <= c <= '9':
                result.append("number")
            else:
                result.append(c)

        return ''.join(result) # 在python里面 '' 和 ""没有区别

if __name__ == "__main__":
    s = input().strip()
    sol = Solution() # Solution 记得加 ()
    print(sol.replaceDigits(s))
```

### 双指针法

```{python}
# 这个解法的思路是：先统计字符串中数字的个数，从而计算出替换后字符串的最终长度，然后一次性分配好结果数组，再使用两个指针分别从原字符串和结果数组的末尾向前移动，遇到数字就在结果数组中从后往前填入 `"number"`，遇到字母则直接复制，最终将结果数组拼接成字符串返回。
class Solution:
    def replaceDigits(self, s:str) -> str:
        count = sum(1 for char in s if char.isdigit()) # 先数出来一共有多少个digit
        expand_len = len(s) + count * 5 # 每一个digit被替换成'number'的时候都会多占5个格子
        res = [''] * expand_len

        old_index = len(s) - 1
        new_index = expand_len - 1

        while old_index >= 0:
            if s[old_index].isdigit():
                # Python 切片是「左闭右开」，所以右边的index要 + 1
                res[new_index -5 : new_index + 1] = "number" 
                new_index -= 6
            else:
                res[new_index] = s[old_index]
                new_index -= 1
            old_index -= 1

        return ''.join(res)

if __name__ == "__main__":
    sol = Solution()

    while True:
        try:
            s = input()
            print(sol.replaceDigits(s))
        except EOFError:
            break
```